# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: pastebinBackend
    build: .
    command: gunicorn -b 0.0.0.0:5000 pastebinBackend.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/pastebinBackend.db
    volumes:
      - ./pastebinBackend:/code/pastebinBackend
      - ./db/:/db/
    ports:
      - "5000:5000"
