"""empty message

Revision ID: 2430a27b4d43
Revises: e66d4e690f9a
Create Date: 2022-04-26 23:19:39.674868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2430a27b4d43'
down_revision = 'e66d4e690f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paste_user_id_fkey', 'paste', type_='foreignkey')
    op.drop_column('paste', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('paste_user_id_fkey', 'paste', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
