"""empty message

Revision ID: 91a5a454c2d5
Revises: 2430a27b4d43
Create Date: 2022-04-28 16:04:53.387467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a5a454c2d5'
down_revision = '2430a27b4d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paste', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paste', type_='foreignkey')
    op.drop_column('paste', 'user_id')
    # ### end Alembic commands ###
